### ISSUE TITLE
Error: Cannot find module 'azure-pipelines-task-lib/task'

### ISSUE THREAD

**Issue by AndrewCopeland** [AndrewCopeland/conjur-extension-azure-devops#4]
```
Error: Cannot find module 'azure-pipelines-task-lib/task'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/vsts/work/_tasks/GetConjurSecret_e9c84774-b108-43c0-b04a-7cfaa4ad6906/1.2.12/index.js:15:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by AndrewCopeland** [comment]
Resolved in this commit: https://github.com/AndrewCopeland/conjur-extension-azure-devops/commit/0a611fc2b6543f53748e4aeccb4d639df63b4b95
